// <auto-generated />
using System;
using BackupService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackupService.Database.Migrations
{
    [DbContext(typeof(BackupDbContext))]
    [Migration("20260629070755_RemoveProfileDescription")]
    partial class RemoveProfileDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("BackupService.Database.AdminCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminCredentials");
                });

            modelBuilder.Entity("BackupService.Database.AppOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowTrayIcon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartWithWindows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppOptions");
                });

            modelBuilder.Entity("BackupService.Database.ArchiveSyncFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchiveSyncItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveSyncItemId");

                    b.ToTable("ArchiveSyncFilters");
                });

            modelBuilder.Entity("BackupService.Database.ArchiveSyncItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompressionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EncryptionMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeSubFolders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLevels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnlyCopyOnChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordEncrypted")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PasswordProtect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SourceConnectionId");

                    b.HasIndex("TargetConnectionId");

                    b.ToTable("ArchiveSyncItems");
                });

            modelBuilder.Entity("BackupService.Database.AuthenticationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AuthenticationHistory");
                });

            modelBuilder.Entity("BackupService.Database.BackupRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BackupRecords");
                });

            modelBuilder.Entity("BackupService.Database.BackupRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesCopied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Copied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Errors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Manual")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OperationLogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduledTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Updated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warnings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ScheduledTaskId");

                    b.ToTable("BackupRuns");
                });

            modelBuilder.Entity("BackupService.Database.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("BackupService.Database.FolderPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowDeletions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSubFolders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastRunStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("OverwriteBehaviour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SourceConnectionId");

                    b.HasIndex("TargetConnectionId");

                    b.ToTable("FolderPairs");
                });

            modelBuilder.Entity("BackupService.Database.FolderPairFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolderPairId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderPairId");

                    b.ToTable("FolderPairFilters");
                });

            modelBuilder.Entity("BackupService.Database.GoogleDriveConnectionSettings", b =>
                {
                    b.Property<int>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecretEncrypted")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshTokenEncrypted")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootFolder")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsesBuiltInClient")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConnectionId");

                    b.ToTable("GoogleDriveConnectionSettings");
                });

            modelBuilder.Entity("BackupService.Database.InstantSyncItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowDeletions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DebounceMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSubFolders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SourceConnectionId");

                    b.HasIndex("TargetConnectionId");

                    b.ToTable("InstantSyncItems");
                });

            modelBuilder.Entity("BackupService.Database.LightroomArchiveItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowDeletions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DebounceMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSubFolders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("TargetConnectionId");

                    b.ToTable("LightroomArchiveItems");
                });

            modelBuilder.Entity("BackupService.Database.LogRetentionSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthenticationLogRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationLogRetentionDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LogRetentionSettings");
                });

            modelBuilder.Entity("BackupService.Database.OperationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("OperationLogs");
                });

            modelBuilder.Entity("BackupService.Database.OperationLogDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationLogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationLogId");

                    b.ToTable("OperationLogDetails");
                });

            modelBuilder.Entity("BackupService.Database.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateLastRun")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateNextRun")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("HandleMissedSync")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LightroomFolder")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawFolderName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawFormats")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Schedule")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("BackupService.Database.ScheduledTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateLastRun")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateNextRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HandleMissedSync")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Schedule")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScheduledTasks");
                });

            modelBuilder.Entity("BackupService.Database.ScheduledTaskStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arguments")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RunViaShell")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduledTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Script")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledTaskId");

                    b.ToTable("ScheduledTaskSteps");
                });

            modelBuilder.Entity("BackupService.Database.SmbConnectionSettings", b =>
                {
                    b.Property<int>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Domain")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootFolder")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionId");

                    b.ToTable("SmbConnectionSettings");
                });

            modelBuilder.Entity("BackupService.Database.UsbConnectionSettings", b =>
                {
                    b.Property<int>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareSerial")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MtpSerial")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootFolder")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeSerial")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionId");

                    b.ToTable("UsbConnectionSettings");
                });

            modelBuilder.Entity("BackupService.Database.ArchiveSyncFilter", b =>
                {
                    b.HasOne("BackupService.Database.ArchiveSyncItem", "ArchiveSyncItem")
                        .WithMany("Filters")
                        .HasForeignKey("ArchiveSyncItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveSyncItem");
                });

            modelBuilder.Entity("BackupService.Database.ArchiveSyncItem", b =>
                {
                    b.HasOne("BackupService.Database.Profile", "Profile")
                        .WithMany("ArchiveSyncItems")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackupService.Database.Connection", "SourceConnection")
                        .WithMany()
                        .HasForeignKey("SourceConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackupService.Database.Connection", "TargetConnection")
                        .WithMany()
                        .HasForeignKey("TargetConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Profile");

                    b.Navigation("SourceConnection");

                    b.Navigation("TargetConnection");
                });

            modelBuilder.Entity("BackupService.Database.BackupRun", b =>
                {
                    b.HasOne("BackupService.Database.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BackupService.Database.ScheduledTask", "ScheduledTask")
                        .WithMany()
                        .HasForeignKey("ScheduledTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("BackupService.Database.FolderPair", b =>
                {
                    b.HasOne("BackupService.Database.Profile", "Profile")
                        .WithMany("FolderPairs")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackupService.Database.Connection", "SourceConnection")
                        .WithMany()
                        .HasForeignKey("SourceConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackupService.Database.Connection", "TargetConnection")
                        .WithMany()
                        .HasForeignKey("TargetConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Profile");

                    b.Navigation("SourceConnection");

                    b.Navigation("TargetConnection");
                });

            modelBuilder.Entity("BackupService.Database.FolderPairFilter", b =>
                {
                    b.HasOne("BackupService.Database.FolderPair", "FolderPair")
                        .WithMany("Filters")
                        .HasForeignKey("FolderPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FolderPair");
                });

            modelBuilder.Entity("BackupService.Database.GoogleDriveConnectionSettings", b =>
                {
                    b.HasOne("BackupService.Database.Connection", "Connection")
                        .WithOne("GoogleDrive")
                        .HasForeignKey("BackupService.Database.GoogleDriveConnectionSettings", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("BackupService.Database.InstantSyncItem", b =>
                {
                    b.HasOne("BackupService.Database.Profile", "Profile")
                        .WithMany("InstantSyncItems")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackupService.Database.Connection", "SourceConnection")
                        .WithMany()
                        .HasForeignKey("SourceConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackupService.Database.Connection", "TargetConnection")
                        .WithMany()
                        .HasForeignKey("TargetConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Profile");

                    b.Navigation("SourceConnection");

                    b.Navigation("TargetConnection");
                });

            modelBuilder.Entity("BackupService.Database.LightroomArchiveItem", b =>
                {
                    b.HasOne("BackupService.Database.Profile", "Profile")
                        .WithMany("LightroomArchiveItems")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackupService.Database.Connection", "TargetConnection")
                        .WithMany()
                        .HasForeignKey("TargetConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Profile");

                    b.Navigation("TargetConnection");
                });

            modelBuilder.Entity("BackupService.Database.OperationLog", b =>
                {
                    b.HasOne("BackupService.Database.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("BackupService.Database.OperationLogDetail", b =>
                {
                    b.HasOne("BackupService.Database.OperationLog", "OperationLog")
                        .WithMany("Details")
                        .HasForeignKey("OperationLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationLog");
                });

            modelBuilder.Entity("BackupService.Database.ScheduledTaskStep", b =>
                {
                    b.HasOne("BackupService.Database.ScheduledTask", "ScheduledTask")
                        .WithMany("Steps")
                        .HasForeignKey("ScheduledTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("BackupService.Database.SmbConnectionSettings", b =>
                {
                    b.HasOne("BackupService.Database.Connection", "Connection")
                        .WithOne("Smb")
                        .HasForeignKey("BackupService.Database.SmbConnectionSettings", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("BackupService.Database.UsbConnectionSettings", b =>
                {
                    b.HasOne("BackupService.Database.Connection", "Connection")
                        .WithOne("Usb")
                        .HasForeignKey("BackupService.Database.UsbConnectionSettings", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("BackupService.Database.ArchiveSyncItem", b =>
                {
                    b.Navigation("Filters");
                });

            modelBuilder.Entity("BackupService.Database.Connection", b =>
                {
                    b.Navigation("GoogleDrive");

                    b.Navigation("Smb");

                    b.Navigation("Usb");
                });

            modelBuilder.Entity("BackupService.Database.FolderPair", b =>
                {
                    b.Navigation("Filters");
                });

            modelBuilder.Entity("BackupService.Database.OperationLog", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("BackupService.Database.Profile", b =>
                {
                    b.Navigation("ArchiveSyncItems");

                    b.Navigation("FolderPairs");

                    b.Navigation("InstantSyncItems");

                    b.Navigation("LightroomArchiveItems");
                });

            modelBuilder.Entity("BackupService.Database.ScheduledTask", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
